Drop Node.js v8 support, Release v1
serverlessinc/utils-china pull request #52
Opened 2020-09-18 11:44 UTC by medikoo

It's to ensure that Serverless Framework that bundles that package is free from security issues, and that outdated package versions are not used:

Maintanance improvement, that covers:
- General CI improvements
- Drop of support to Node.js v8
- Seclude npmignore rules from CI config to `.npmignore` file
- Update `winston` dependency reference to `package.json` so patch and minor updates are respected
- Remove `object-assign` dependency (native `Object.assign` is well supported in Node.js v4+)
- Release as `1.0.0`, as we need a major bump, and this package is already intended for production, so there seems no reason to use 0.x release numbers

2020-09-18 21:37 UTC, hkbarton approved these changes

2020-09-19 10:07 UTC, yugasun requested changes

2020-09-21 09:20 UTC, medikoo commented on package.json
> +    "winston": "^3.2.1"
@yugasun thanks for pointing that. I've reverted that change. It was not clear to me, and unfortunately `package.json` doesn't support comments to properly flag this

2020-09-21 10:00 UTC, timqian approved these changes

2020-09-21 13:46 UTC, merged