将登录模块/实名认证api/角色信息api新增至dev环境
serverlessinc/utils-china pull request #64
Opened 2020-10-27 09:20 UTC by Jominja

通过判断.env文件中的SERVERLESS_PLATFORM_STAGE变量，路由至上海测试环境

2020-10-27 10:44 UTC, timqian commented
Seems you need to run `npm run prettify`

2020-10-28 05:00 UTC, Jominja commented on sdk/account/getUserAuthInfo.js
> +  checkEnvUrl() {
done

2020-10-28 05:10 UTC, yugasun requested changes

2020-10-28 05:10 UTC, yugasun commented on sdk/account/getUserAuthInfo.js
> +const apiBaseUrl = 'service-ocnymoks-1258344699.gz.apigw.tencentcs.com';
这另个配合变量也一起提炼下吧

2020-10-28 05:14 UTC, Jominja commented on sdk/account/getUserAuthInfo.js
> +const apiBaseUrl = 'service-ocnymoks-1258344699.gz.apigw.tencentcs.com';
这里我理解从模块的角度上来说直接把url划分到那个具体模块就好了。使用apigw的仅仅只有这此涉及修改的三个部分，其余的api访问都是在云api实现的。

2020-10-28 06:40 UTC, yugasun commented on sdk/account/getUserAuthInfo.js
> +const apiBaseUrl = 'service-ocnymoks-1258344699.gz.apigw.tencentcs.com';
同样都是后端服务接口，而且 `account` 和 `cam`  两个模块都是一个服务，不应该个字两个子函数分别写一遍，这种通用的服务接口域名前缀放到通用的配置文件中应该更好一些

2020-10-28 06:47 UTC, yugasun approved these changes

2020-10-28 06:55 UTC, Jominja commented on sdk/account/getUserAuthInfo.js
> +const apiBaseUrl = 'service-ocnymoks-1258344699.gz.apigw.tencentcs.com';
事实上bindRole和authUserInfo从sf的业务角度来说，访问的是sf内部封装的接口，功能上和account还有cam也不一样，后续也可以单独放到一个文件夹中

2020-10-28 09:44 UTC, merged