Call cliCallback when socket error appears
serverlessinc/utils-china pull request #82
Opened 2022-01-05 10:55 UTC by timqian

related ticket: https://app.asana.com/0/1200011502754281/1201504159421230

2022-01-06 02:29 UTC, ole3021 requested changes

2022-01-06 02:29 UTC, ole3021 commented on sdk/debug/lib/wshub-client/index.js
> +      cliCallback('Socket 连接出错，请检查您的网络连接是否正常', { type: 'error' });
'连接错误，请检查网络连接后重试'

2022-01-06 02:29 UTC, ole3021 commented on sdk/debug/lib/wshub-client/index.js
> +        cliCallback('Socket 连接超时，请检查您的网络连接是否正常', { type: 'error' });
'连接超时，请检查网络连接后重试'

2022-01-06 02:31 UTC, ole3021 requested changes

2022-01-06 02:31 UTC, ole3021 commented on sdk/debug/lib/wshub-client/index.js
> +        cliCallback('Socket 连接超时，请检查您的网络连接是否正常', { type: 'error' });
'连接超时，请检查网络连接后重试'

2022-01-06 02:31 UTC, ole3021 commented on sdk/debug/lib/wshub-client/index.js
> +      cliCallback('Socket 连接出错，请检查您的网络连接是否正常', { type: 'error' });
'连接错误，请检查网络连接后重试'

2022-01-07 02:00 UTC, timqian commented on sdk/debug/lib/wshub-client/index.js
> +      cliCallback('Socket 连接出错，请检查您的网络连接是否正常', { type: 'error' });
已更新

2022-01-12 06:06 UTC, merged